### ISSUE TITLE
Create a Daily Report

### ISSUE THREAD

**Issue by pbchase** [ctsit/tt_reporting#15]
Create a Daily Report with a short list of summary metrics and one or more visualizations. 

The title of the report should be something like "UF Health Screen, Test & Protect Daily Contact Tracing report as of `r report_end_date`".  The report should show:

1. Total number of positive individuals STP has investigated (for all time), categorized by person_type. For definition of these records, steal code from https://github.com/ctsit/tt_reporting/blob/86203587f3ff264db6a16aa696ab5b1a50cbc46f/uf_stp_report.Rmd#L57 
1. Current number of people quarantined or isolated (at this time), categorize by person_type. For definition of these records, steal code from these places: https://github.com/ctsit/tt_reporting/blob/86203587f3ff264db6a16aa696ab5b1a50cbc46f/uf_stp_report.Rmd#L65 https://github.com/ctsit/tt_reporting/blob/86203587f3ff264db6a16aa696ab5b1a50cbc46f/uf_stp_report.Rmd#L84 https://github.com/ctsit/tt_reporting/blob/86203587f3ff264db6a16aa696ab5b1a50cbc46f/uf_stp_report.Rmd#L89 

The first section of the data should be labeled  "Total number of positive individuals STP has investigated to as of `r report_end_date`".
The 2nd section of the data should be labeled  "Current number of people quarantined or isolated as of `r report_end_date`".
Alongside the second table, include a note that reads "The count of quarantined people includes UF students and employees as well as  people with no direct affiliation to UF such as family members and roommates."

For person_type data, see https://github.com/ctsit/tt_reporting/blob/86203587f3ff264db6a16aa696ab5b1a50cbc46f/uf_stp_report.Rmd#L52  Know that lots of contacts will be non-UF. They will have no person type. Outer join the contact data to person_type data to assure these non-UF people are not dropped from the contacts.

Mutate the person_type labels as follows:
- Employee -> UF Employee
- Student -> UF Student
- Both -> UF Employee and Student
- Other -> Employee of a UF Affiliate
- NA -> Non-UF
- JAX -> UF Employee or Student Located in Jacksonville

My hope is these labels will reduce some of the ambiguity of the person_type data.

Create both a csv of summary data and PDF. The script should send both files via email.  Initially the files should be delivered to Kelly, Jerne, Philip, and Chris.

**Comment by ljwoodley** [comment]
Addressed by issue #21
