### ISSUE TITLE
Add statistics about contacts-per-case to the weekly report

### ISSUE THREAD

**Issue by pbchase** [ctsit/tt_reporting#16]
Add statistics about contacts-per-case to the weekly report. 

To get this data, read the Contacts database. Group the contacts data by `case_id`. Produce basic statistics to characterize the number of contacts per case. Produce the same statistics for each of the person_type categories. Consider showing these results on a set of whisker plots (would that be faceted whisker plots???)

As in issue #15, mutate the person_type labels as follows:
- Employee -> UF Employee
- Student -> UF Student
- Both -> UF Employee and Student
- Other -> Employee of a UF Affiliate
- NA -> Non-UF
- JAX -> UF Employee or Student Located in Jacksonville

**Comment by ChemiKyle** [comment]
Addressed by PR #20
