### ISSUE TITLE
Research a refined data for the epicurve

### ISSUE THREAD

**Issue by pbchase** [ctsit/tt_reporting#22]
The date used in the current epicurve is `case_report_datetime`.  While this is the most commonly available date, it is also the least accurate date. The normal date epidemiologists use is the date of disease onset, yet that not universally available. I proposed a compromise to the contact tracing team wherein we would use the best data we have for each case. At the very least the result is easy to code. We would only need to coalesce the right fields in the right order. This is what the contact tracing team thought would be the right order:

```
case_data %>% 
    mutate(epicurve_date = coalesce(case_sx_onset_date, case_lab_collect_date, case_lab_report_date, case_report_datetime)) 
```

Could you add this in a PR along with an analysis that shows in summary how much each date field contributes to the epicurve_date? Could you provide summary statics on the difference between `epicurve_date` and the `case_report_datetime`?

**Comment by ljwoodley** [comment]
Addressed by PR #34
