### ISSUE TITLE
Calculate weekly reporting dates dynamically

### ISSUE THREAD

**Issue by pbchase** [ctsit/tt_reporting#31]
Calculate weekly reporting dates dynamically in `weekly_report.Rmd`.  We have been updating these lines each week:

```
end_date <- ymd_hms("2020-07-19 23:59:59")
last_week <- interval(ymd("2020-07-13"), end_date)
```
We need to compute these automatically, so that, for example, running the report on 2020-07-20 - 2020-07-26 would uses the data as of "2020-07-19 23:59:59".

**Comment by ljwoodley** [comment]
addressed by PR #33
