### ISSUE TITLE
Run weekly_report.Rmd via cron

### ISSUE THREAD

**Issue by pbchase** [ctsit/tt_reporting#32]
Run `weekly_report.Rmd` via cron.  

To do this:
1. add a script runner that will run the `weekly_report.Rmd`, name the output file "uf_stp_weekly_report_YYYYMMDDHHMMSS.Rmd" and email it to a configurable list of email addresses. 
1. Add a cron line to `examples/tt_reporting` that runs the script runner.  The job should run each Monday at 00:15. 
1. The output should be mailed to Inyoung, Kelly, Philip, and Laurence.

**Comment by ljwoodley** [comment]
Addressed by PR #39
