### ISSUE TITLE
Add total number of people that have been in isolation/quarantine

### ISSUE THREAD

**Issue by pbchase** [ctsit/tt_reporting#35]
Add total number of people that have been in isolation/quarantine in the `isolated_and_quarantined` dataframe in  https://github.com/ctsit/tt_reporting/blob/master/daily_contact_tracing_report.R

1. Revise the isolated_and_quarantined dataframe
1. Add a data frame column “current_n” that is a copy of ’n’
1. Add a dataframe column named ‘anytime_n’ that is the total number of all people isolated or quarantine at some point since the STP project began, grouped by person_type.

Cognos will require these changes to consume the new file:

1. Rename table “People Currently in Isolation or Quarantine” to “People in Isolation or Quarantine”
1. Rename to column “# in Isolation or Quarantine” to “Currently in Isolation or Quarantine”
1. Add a column in the isolated/quarantine table titled “# Isolated or Quarantined at any time”

The Cognos changes are outside our scope, but we should be careful not to release this  new feature until Cognos is ready to consume it.

**Comment by ljwoodley** [comment]
@pbchase  Are there any rules for:

`Add a dataframe column named ‘anytime_n’ that is the total number of all people isolated or quarantine at some point since the STP project began, grouped by person_type.`

**Comment by pbchase** [comment]
I don't understand the question.  What do you mean by rules?

**Comment by ljwoodley** [comment]
How are finding the total number of people  isolated since data collection began? We're using `cleared_for_campus != 'Y'` for subjects currently isolated but this changes daily.

**Comment by pbchase** [comment]
Do you take issue with the count of contact records?

**Comment by pbchase** [comment]
`n_ever` is a better name then `anytime_n` I made a suggestion on PR #44

**Comment by ljwoodley** [comment]
Addressed by PR #44
