### ISSUE TITLE
Add totals to two tables in daily_contact_tracing_report.R

### ISSUE THREAD

**Issue by pbchase** [ctsit/tt_reporting#36]
In https://github.com/ctsit/tt_reporting/blob/master/daily_contact_tracing_report.R, make two changes to the dataframes `count_of_cases_for_all_time_by_person_type` and `isolated_and_quarantined`.

1. Arrange data by Person_Type
1. Add row to the DF with the sum of `n`

We will need to coordinate this with the cognos team. They will need to stop sorting the the data or the total row will not appear on the bottom. Do not release this change until Cognos is ready for it.

**Comment by pbchase** [comment]
Stop any work on this issue. It looks like the Cognos team handled this themselves.

**Comment by ljwoodley** [comment]
@pbchase I'm closing this issue since it's been solved by the Cognos team.
